sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wjoHNMSsMTorrcMxWXA6Gn8LDS96Jw2d9GNbEh1w/Sc3cpglL+rL+4wnyue1QYeq4bSMkyvxx+OZHyNRWqoVHavTmaX/Fa5ZvlOkdHCudoi76ZVvD3T8H67aAoEX0MDtRsqoZxdJ3SJbivwGDjB1b88aDyZsYBeaGcVZHsvFUeHllWnzGZ+mLUHy/2nKAmQipnkboD5QElKaeaINi45lpFv8jwOO4G50Ir5J+Az2ZGC8KMi3Bd0RTXR1KuvHLBBPM+NYDaOUJz+wRZa7BUGIAZpWTnOS17KOOekbTFEHGON5kO6a49eSANDdWNgLWqGRKiSNjKrq/c/mJnF94m2wE2D2WqGqy2T2mK02Jag+5U4bkolSc0FP6At6N+9g8Nwa2fbMLWrHM7DL28sn4ZDcLb2D93kajPI1pbrMb4NZcl+e3fD1j8xLfnA1OKSLbboTXX+qL7QE2Hv0ms0xt6lkdruPt4z+6xaikrvuyM4pud6V4K8H4Pug8DX5NUQfLBQKh/S9YcuSK4ZJrKW7ecfWC5nGGsAifMHJOEW21UC1lPf9os9CKtHi4pIokyXMg/u61gQKmhgmSIyqVUWZ8XRLUDXRRzTOh5yXSxdDU3UTWUGBusyrYlcsoGMqv/YDJtS5tMkLqVPDYn4oI66CK1x4EKopyTTdvY3VA3j1w8CRbZ4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Millionaire-of-Rough-and-Ready_2280
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy